---
Name: level51-image-credits
---
SilverStripe\Assets\Image:
  extensions:
    - Level51\ImageCredits\ImageExtension

SilverStripe\AssetAdmin\Forms\ImageFormFactory:
  extensions:
    - Level51\ImageCredits\ImageFormFactoryExtension

Level51\ImageCredits\ImageExtension:
  force_rebuild: false
  text_margin: 10
  box_padding: 10
  font_size: 30
  font_color: '#000000'
  box_background: 'rgba(255, 255, 255, 0.7)'
